apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shopnow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 640928554403.dkr.ecr.ap-south-1.amazonaws.com/akplacesolution-shopnow/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongo:27017/shopnow"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: shopnow
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
