apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: shopnow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: 640928554403.dkr.ecr.ap-south-1.amazonaws.com/akplacesolution-shopnow/admin:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /admin/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: shopnow
spec:
  selector:
    app: admin
  ports:
    - port: 80
      targetPort: 80
