apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shopnow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 640928554403.dkr.ecr.ap-south-1.amazonaws.com/akplacesolution-shopnow/frontend:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: shopnow
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
